# https://dev.azure.com/NabuCasa/OpenSource

trigger:
  branches:
    include:
    - master
    - dev
  tags:
    include:
    - '*'
    exclude:
    - untagged*
pr:
- dev

variables:
  - group: twine


jobs:

- job: "Tox"
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: pip install tox
    displayName: 'Install Tox'
  - script: tox
    displayName: 'Run Tox'


- job: 'Black'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: '3.7'
  - script: pip install black
    displayName: 'Install black'
  - script: black --check hass_nabucasa tests
    displayName: 'Run Black'


- job: 'Release'
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags'), succeeded('Tox'), succeeded('Black'))
  dependsOn:
  - 'Tox'
  - 'Black'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: '3.7'
  - script: pip install twine
    displayName: 'Install twine'
  - script: python setup.py sdist
    displayName: 'Build package'
  - script: |
      TWINE_USERNAME="$(twineUser)"
      TWINE_PASSWORD="$(twinePassword)"

      twine upload dist/*
    displayName: 'Upload pypi'
